"""empty message

Revision ID: 1e22a3b8e1cc
Revises: 3395fd89cf83
Create Date: 2019-11-24 13:13:36.192236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e22a3b8e1cc'
down_revision = '3395fd89cf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('forgotten_password_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'forgotten_password_token')
    # ### end Alembic commands ###
