"""empty message

Revision ID: 3395fd89cf83
Revises: 
Create Date: 2019-11-24 13:09:01.743753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3395fd89cf83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continuous_query_recompute_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('cq_name', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=120), nullable=True),
    sa.Column('time_interval_start', sa.DateTime(), nullable=False),
    sa.Column('time_interval_end', sa.DateTime(), nullable=False),
    sa.Column('last_run_start', sa.DateTime(), nullable=True),
    sa.Column('last_run_end', sa.DateTime(), nullable=True),
    sa.Column('last_execution_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('_password', sa.Text(), nullable=True),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('url_picture', sa.Text(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('user_authorized', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_confirmation_token', sa.Text(), nullable=True),
    sa.Column('admin_authorization_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('continuous_query_recompute_job')
    # ### end Alembic commands ###
